# 设置启动端口
server:
  port: 9000
# 配置mapper映射文件
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true




# 本地数据库相关配置
spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/project1
  # 配置redis缓存
  redis:
    host: localhost
    port: 6379
    database: 0

token:
  jwt:
    header: Authentication
    # 加密密钥 32位
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token过期时间(1个小时)
    expire: 3600




