# 设置启动端口
server:
  port: 9000
# 配置mapper映射文件
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true




# 本地数据库相关配置
spring:
  datasource:
    username: admin
    password: 12345678
    url: jdbc:mysql://database-1.co8c9v24smnd.us-east-1.rds.amazonaws.com:3306/project1
  # 配置redis缓存
  redis:
    host: localhost
    port: 6379
    database: 0
spring.datasource.

token:
  jwt:
    header: token
    # 加密密钥 32位
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token过期时间(2个小时)
    expire: 7200

cloud.aws.


# AWS Cloud config
cloud:
  aws:
    credentials:
      access-key: AKIAQFULF3NX2MWQMUFY
      secret-key: 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
    region:
      auto: true

