# 设置启动端口
server:
  port: 9000
# 配置mapper映射文件
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true





spring:
# Local database configuration
#  datasource:
#    username: root
#    password: 12345
#    url: jdbc:mysql://localhost:3306/project1
# AWS database configuration
  datasource:
    username: admin
    password: 123456789
    url: jdbc:mysql://database-1.co8c9v24smnd.us-east-1.rds.amazonaws.com:3306/project1


  # Redis configuration
  redis:
    host: localhost
    port: 6379
    database: 0
#    password: project12345

  # email configuration
  mail:
    host: smtp.126.com
    username: kenlbd61@126.com
    password: CRIQTBGDMQSPMFLF
    protocol: smtps
    port: 465
    properties:
      socketFactory:
        port: 465
        class: javax.net.ssl.SSLSocketFactory
        fallback: false

token:
  jwt:
    header: Authentication
    # encryption key 32 bit
    secret: ji8n3439n439n43ld9ne9343fdfer49h
    # token expired in 1 hour
    expire: 3600




